### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by caseyjohnsonwv** [caseyjohnsonwv/totd-ai#1]
- [x] Create DAG for ingesting TMIO data into Collection layer
- [x] Create DAG for cleaning TMIO data and promoting to Conform
- [x] Create DAG for ingesting TMX data into Collection layer
- [x] Create DAG for cleaning TMX data and promoting to Conform
- [x] Create master orchestration DAG to trigger all aforementioned DAGs sequentially
- [x] Pay down technical debt and use volumes to persist data properly
- [x] Perform one-time load of TMX tags data into Conform layer XREF table
- [x] Create DAGs for loading additional TMX data such as multiple authors, leaderboards, etc
- [x] Create DAGs for loading TMIO leaderboards data to supplement TMX data
- [x] #2
- [x] Revisit technical debt for persistent volumes; create volumes independently from docker-compose stack
- [x] Perform historical load of past TMIO and TMX data
- [ ] Train AI models using views on data from Consume, select one, and bake it into the Airflow environment
- [ ] Create DAG for running AI model with data from Consume and publishing predictions to Application layer
- [ ] Create DAG for demoting old predictions from the Application layer down to an archive in Consume
- [ ] Build FastAPI route `/predictions/{date}` to expose predictions from the Application layer
- [ ] Build FastAPI route `/totd/{date}` to expose actual / historical data from the Consume layer
